import { getRandomNumber } from './randomNumber'

const posts = [
  'Exploring new hiking trails today! 🌲🏞️',
  'Just finished reading an amazing book! 📚',
  'Enjoying a sunny day at the beach. ☀️🏖️',
  'Trying out a new recipe for dinner tonight. 🍲',
  'Attended a fantastic concert last night! 🎸🎤',
  'Weekend getaway to the mountains. 🏔️🏡',
  'Visited an art gallery and felt so inspired. 🎨🖼️',
  'Morning coffee at my favorite café. ☕️🌞',
  'Spending quality time with family today. 👨‍👩‍👧‍👦❤️',
  'Working on a new project, feeling productive! 💻✨',
  'Gardening in the backyard, loving the fresh air. 🌸🌿',
  'Had a fun movie night with friends. 🎥🍿',
  "Learning a new language, it's challenging but fun! 🌍📖",
  'Tried a new workout routine, feeling great! 💪🏋️',
  "Exploring the local farmers' market. 🥕🍅",
  'Taking a relaxing stroll in the park. 🌳🚶‍♂️',
  'Baking some delicious cookies today. 🍪👩‍🍳',
  'Caught up with an old friend over lunch. 🍴😊',
  'Enjoying a peaceful evening at home. 🏠✨',
  'Visited a nearby museum, learned so much! 🏛️📚',
  'Listening to my favorite music all day. 🎶🎧',
  'Crafting some DIY home decor. 🏡🎨',
  'Spending the afternoon sketching. ✏️📓',
  'Attended a workshop on digital marketing. 💼📈',
  'Exploring new tech gadgets. 📱💻',
  'Planning my next travel adventure. ✈️🌏',
  'Trying out a new café in town. ☕️🍰',
  'Had a relaxing spa day, feeling rejuvenated. 💆‍♀️💖',
  'Went for a long bike ride this morning. 🚴‍♂️🌄',
  'Discovered a hidden gem of a bookstore. 📚📖',
  'Attended a local theater performance. 🎭👏',
  'Spending the day volunteering at a shelter. 🐶💚',
  'Experimenting with some new photography techniques. 📸🌇',
  'Cooking up a storm in the kitchen today! 🍳🥘',
  'Took a day trip to a nearby city. 🏙️🚗',
  'Exploring the wonders of nature. 🌼🍃',
  'Had an amazing brunch with friends. 🥞🥂',
  'Started a new painting today. 🎨🖌️',
  'Went for a swim at the local pool. 🏊‍♂️🏊‍♀️',
  'Exploring local history at the museum. 🏛️🗺️',
  'Enjoying a quiet evening reading a novel. 📖🕯️',
  'Playing board games with the family tonight. 🎲🃏',
  'Attended a yoga class, feeling zen. 🧘‍♂️🧘‍♀️',
  'Walking the dog in the evening breeze. 🐕🌅',
  'Catching up on my favorite TV series. 📺🍿',
  'Having a picnic in the park. 🧺🌞',
  'Visited a nearby botanical garden. 🌷🌿',
  'Enjoying a homemade pizza night. 🍕🍴',
  'Working on a new blog post. 📝🌐',
  'Just finished a challenging puzzle. 🧩🤔',
  'Went on a photography walk. 📸🏙️',
  'Tried out a new restaurant in town. 🍽️🍷',
  'Had a lovely day at the zoo. 🦁🐧',
  'Taking a pottery class, so much fun! 🏺👩‍🎨',
  'Attended a live sports event. 🏀🏟️',
  'Enjoying some homemade ice cream. 🍦🍨',
  'Reading a fascinating biography. 📚👤',
  'Visited a science center, so interesting! 🔬🧪',
  'Working on some creative writing. ✍️📝',
  'Had a wonderful afternoon tea. ☕️🍰',
  'Went for a scenic drive. 🚗🌄',
  'Exploring local cafes for the best coffee. ☕️🧐',
  'Spent the day at a music festival. 🎵🎤',
  'Had a productive day organizing my workspace. 🗂️✨',
  'Tried making homemade pasta, it was delicious! 🍝👨‍🍳',
  'Visited a historical site, learned a lot! 🏰📜',
  'Spent the evening star gazing. 🌌🔭',
  'Had a relaxing day at the beach. 🏖️🌊',
  'Working on a new sewing project. 🧵✂️',
  'Went for a run in the morning. 🏃‍♂️🌅',
  'Trying out new meditation techniques. 🧘‍♀️🧘‍♂️',
  'Had a movie marathon with classic films. 🎥🎬',
  'Exploring the local aquarium. 🐠🐟',
  'Had an awesome game night with friends. 🎮🕹️',
  'Visited a craft fair, so many unique items! 🛍️🎨',
  'Attended a community event, met great people! 👥🎉',
  'Spent the afternoon people-watching at a café. ☕️👀',
  'Learning about new cultures through documentaries. 🌏📺',
  'Exploring local markets for fresh produce. 🍎🍓',
  'Had a relaxing day at home, just what I needed. 🏠💤',
  'Visited a local winery, enjoyed the tastings. 🍇🍷',
  'Started planning my garden for the spring. 🌻🌱',
  'Learning to play a new musical instrument. 🎸🎹',
  'Had a fun photoshoot with friends. 📸😊',
  'Went to a comedy show, laughed so much! 😂🎤',
  'Exploring new music genres. 🎧🎶',
  'Attended a book club meeting, great discussion! 📚💬',
  'Experimenting with different coffee brewing methods. ☕️🔬',
  'Went for a scenic hike this morning. 🥾🌲',
  'Spent the day baking bread. 🍞👨‍🍳',
  'Visited a local fair, so much fun! 🎡🎟️',
  'Learning about sustainable living. 🌱🌍',
  'Had a great workout session. 🏋️‍♀️💪',
  'Enjoyed a peaceful boat ride. 🚤🛶',
  'Tried a new dance class, it was amazing! 💃🕺',
  'Visited a local farm, so many cute animals! 🐮🐷',
  'Had a productive brainstorming session. 💡📝',
  'Attended a tech conference, learned so much! 💻📈',
  'Enjoying some fresh homemade lemonade. 🍋🍹',
  'Went for a sunset walk, so beautiful! 🌅🚶‍♀️',
  'Spending the day relaxing and unwinding. 🛋️💆‍♂️',
  'Started learning a new coding language. 💻👨‍💻',
  'Had a delicious sushi dinner. 🍣🍱',
  'Exploring the wonders of the night sky. 🌌🌠'
]

export const randomPosts = () => {
  const quantity = getRandomNumber(0, 7)
  const numArr: number[] = []
  while (numArr.length !== quantity) {
    let number = getRandomNumber(0, posts.length)
    if (!numArr.includes(number)) {
      numArr.push(number)
    }
  }
  return numArr.map(n => posts[n])
}
